#pragma once
#include <string>
#include <iostream>
#include <chrono>
#include <iomanip>
#include <ctime>
#include <random>
#include <SFML/Graphics.hpp>

enum MessageType { info, debug, warning, error, success };
enum ConnType { Undefined, TCP, UDP };

class Utils
{
public:
	static void printMsg(std::string msg, MessageType type = info) {

		if (type != error && !printMessages) return;

		const auto now = std::chrono::system_clock::now();
		const std::time_t currentTime = std::chrono::system_clock::to_time_t(now);
		std::tm localTime = {};
		localtime_s(&localTime, &currentTime);
		const auto timestamp = std::put_time(&localTime, "%Y-%m-%d %H:%M:%S");

		switch (type)
		{
		case debug: std::cout << "\033[36m" << timestamp << "   " << msg << "\033[0m" << std::endl; break;
		case warning: std::cout << "\033[33m" << timestamp << "   " << msg << "\033[0m" << std::endl; break;
		case error: std::cout << "\033[1;31m" << timestamp << "   " << msg << "\033[0m" << std::endl; break;
		case success: std::cout << "\033[1;32m" << timestamp << "   " << msg << "\033[0m" << std::endl; break;
		default: std::cout << timestamp << "   " << msg << std::endl; break;
		}
	}

	static std::string getUserInput() {
		std::string input_line;
		std::getline(std::cin, input_line);
		return input_line;
	}

	static void togglePrints(bool on) {
		printMessages = true;
		if (on) {
			Utils::printMsg("Enabled message printing! Disable with X.");
		}
		else {
			Utils::printMsg("Disabled message printing! Enable with O.");
		}
		printMessages = on;
	}

private:
	inline static bool printMessages = true;
};

class Random {
public:
	// the last seed generated by newRandomSeed
	inline static uint16_t randSeed;

	// the random number generation engine
	inline static std::mt19937 engine;

	// generates a new random seed, and seeds the engine with it
	static void newRandomSeed() {
		const auto now = std::chrono::system_clock::now().time_since_epoch();
		randSeed = now.count();	// intentional narrowing conversion, 65k possible seeds is ok
		engine.seed(randSeed);
	}

	// random float in range
	static float randFloat(std::uniform_real_distribution<float> dist) {
		return dist(engine);
	}

	// random int in range
	static float randInt(std::uniform_int_distribution<int> dist) {
		return dist(engine);
	}
};

// todo: i might not even need this
struct RectF {
	float top, left, bottom, right = 0.0f;
	float width, height = 0.0f;

	sf::Vector2f position;
	sf::Vector2f size;
	sf::Vector2f center;

	RectF(sf::FloatRect r) {
		left = r.position.x;
		right = r.position.x + r.size.x;
		top = r.position.y;
		bottom = r.position.y + r.size.y;

		height = bottom - top;
		width = right - left;

		position = r.position;
		size = r.size;
		center = r.getCenter();
	}
};

// todo: maybe expand later to generic templated object pool
class IdPool
{
public:
	IdPool(size_t idCount) {
		numIds = idCount;
		idsOccupiedList.resize(numIds, false);
	}

	int getFreeID() {
		for (int i = 0; i < numIds; i++) {
			if (idsOccupiedList[i] == false) return i;
		}
		return -1;
	}

	void setIDInUse(int id, bool inUse) {
		idsOccupiedList[id] = inUse;
	}

private:
	size_t numIds;
	std::vector<bool> idsOccupiedList;
};